# Generated by Django 6.0.6 on 2026-06-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projeto_turma_usuario_turma_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='membros_grupo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Membros do Grupo'),
        ),
    ]
